#!/usr/bin/env bash
# ============================================================
# start-deeptutor.sh — launch or restart DeepTutor
# ============================================================
# - First run: clones the repo, prompts for Ollama model,
#   writes .env / compose override, starts container.
# - Subsequent runs: stops existing container, restarts.
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DEEPTUTOR_DIR="$SCRIPT_DIR"
OBSIDIAN_DT="$PROJECT_ROOT/obsidian/deeptutor"

COMPOSE_BASE="$DEEPTUTOR_DIR/DeepTutor/docker-compose.ghcr.yml"
OVERRIDE_FILE="$DEEPTUTOR_DIR/docker-compose.override.yml"
ENV_FILE="$DEEPTUTOR_DIR/DeepTutor/.env"
DT_REPO="$DEEPTUTOR_DIR/DeepTutor"

# Detect whether this is a fresh install
IS_FRESH=false
if [ ! -f "$ENV_FILE" ]; then
  IS_FRESH=true
fi

echo "============================================================"
if $IS_FRESH; then
  echo " DeepTutor — first-time setup + launch"
else
  echo " DeepTutor — restart"
fi
echo "============================================================"

# -------------------------------------------------------------------
# Prerequisites
# -------------------------------------------------------------------
echo ""
echo "==> Checking prerequisites"

if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not installed. Install it first."
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo "ERROR: 'docker compose' plugin not found."
  exit 1
fi

echo "     Docker $(docker --version | cut -d' ' -f3 | tr -d ',') ✓"

if ! command -v ollama &>/dev/null; then
  echo "     ⚠  Ollama not found — install it first"
else
  echo "     Ollama $(ollama --version 2>/dev/null || echo '✓')"
fi

# -------------------------------------------------------------------
# Install step (clone repo + configure env)
# -------------------------------------------------------------------
if [ ! -d "$DT_REPO/.git" ]; then
  echo ""
  echo "==> Cloning DeepTutor"
  git clone https://github.com/HKUDS/DeepTutor.git "$DT_REPO"
fi

if $IS_FRESH; then
  echo ""
  echo "==> First-time configuration"

  echo ""
  echo "==> Creating data directories under obsidian/deeptutor/"
  mkdir -p "$OBSIDIAN_DT/user"
  mkdir -p "$OBSIDIAN_DT/memory"
  mkdir -p "$OBSIDIAN_DT/knowledge_bases"
  echo "     $OBSIDIAN_DT/user"
  echo "     $OBSIDIAN_DT/memory"
  echo "     $OBSIDIAN_DT/knowledge_bases"

  echo ""
  echo "==> Selecting models"

  if ! command -v ollama &>/dev/null; then
    echo "ERROR: Ollama not found. Cannot auto-detect models."
    exit 1
  fi

  AVAILABLE_MODELS=$(ollama list 2>/dev/null | tail -n +2 | awk '{print $1}' | grep -v 'nomic-embed-text')
  HAS_EMBED=$(ollama list 2>/dev/null | tail -n +2 | awk '{print $1}' | grep -c 'nomic-embed-text' || true)

  echo ""
  echo "     Available chat models:"
  echo "$AVAILABLE_MODELS" | while IFS= read -r m; do
    [ -n "$m" ] && echo "       - $m"
  done
  echo ""

  DEFAULT_LLM=$(echo "$AVAILABLE_MODELS" | grep 'deepseek' | head -1)
  [ -z "$DEFAULT_LLM" ] && DEFAULT_LLM=$(echo "$AVAILABLE_MODELS" | head -1)

  echo -n "     Chat model [$DEFAULT_LLM]: "
  read -r SELECTED_LLM
  LLM_MODEL="${SELECTED_LLM:-$DEFAULT_LLM}"

  if [ "$HAS_EMBED" -gt 0 ]; then
    EMBED_MODEL="nomic-embed-text"
    EMBED_HOST="http://localhost:11434/api/embed"
  else
    echo ""
    echo "     ⚠  'nomic-embed-text' not found. KB/RAG won't work."
    echo "     Pull it later: ollama pull nomic-embed-text"
    EMBED_MODEL="nomic-embed-text"
    EMBED_HOST="http://localhost:11434/api/embed"
  fi

  cat > "$ENV_FILE" << EOF
BACKEND_PORT=8001
FRONTEND_PORT=3782
LLM_BINDING=ollama
LLM_MODEL=${LLM_MODEL}
LLM_API_KEY=ollama
LLM_HOST=http://localhost:11434/v1
LLM_REASONING_EFFORT=high
EMBEDDING_BINDING=ollama
EMBEDDING_MODEL=${EMBED_MODEL}
EMBEDDING_API_KEY=ollama
EMBEDDING_HOST=${EMBED_HOST}
SEARCH_PROVIDER=duckduckgo
EOF

  echo "     .env written (LLM=$LLM_MODEL, EMBED=$EMBED_MODEL) ✓"
fi

# -------------------------------------------------------------------
# Compose override (always regenerate — paths may change between repos)
# -------------------------------------------------------------------
echo ""
echo "==> Writing compose override"

cat > "$OVERRIDE_FILE" << OVERRIDE_EOF
# Generated by start-deeptutor.sh — do not edit manually.
# network_mode: host so the container can reach Ollama at localhost:11434.
services:
  deeptutor:
    network_mode: host
    networks: !reset []
    volumes:
      - ${OBSIDIAN_DT}/user:/app/data/user
      - ${OBSIDIAN_DT}/memory:/app/data/memory
      - ${OBSIDIAN_DT}/knowledge_bases:/app/data/knowledge_bases
      - ${PROJECT_ROOT}/obsidian/wiki:/app/data/wiki_mount:ro
OVERRIDE_EOF

echo "     Done ✓"

# -------------------------------------------------------------------
# Stop existing container if running
# -------------------------------------------------------------------
echo ""
echo "==> Stopping existing container (if any)"

cd "$DEEPTUTOR_DIR"

RUNNING=$(docker ps -a --filter name=deeptutor --format '{{.ID}}' 2>/dev/null || true)
if [ -n "$RUNNING" ]; then
  echo "     Container found — shutting down..."
  docker compose -f "$COMPOSE_BASE" -f "$OVERRIDE_FILE" down --remove-orphans 2>/dev/null || \
    (docker stop deeptutor 2>/dev/null; docker rm deeptutor 2>/dev/null; true)
  echo "     Stopped ✓"
else
  echo "     No running container ✓"
fi

# -------------------------------------------------------------------
# Clean stale settings ONLY on fresh install (restarts preserve KB)
# -------------------------------------------------------------------
if $IS_FRESH; then
  if [ -d "$OBSIDIAN_DT/user/settings" ] || [ -d "$OBSIDIAN_DT/knowledge_bases/wiki" ]; then
    echo ""
    echo "==> Cleaning stale cached state"
    docker run --rm -v "$OBSIDIAN_DT":/data alpine sh -c "rm -rf /data/user/settings /data/knowledge_bases" 2>/dev/null || true
    mkdir -p "$OBSIDIAN_DT/knowledge_bases"
    echo "     Done ✓"
  fi
fi

# -------------------------------------------------------------------
# Start
# -------------------------------------------------------------------
echo ""
echo "==> Starting DeepTutor"

docker compose -f "$COMPOSE_BASE" -f "$OVERRIDE_FILE" up -d 2>&1

echo ""
echo "============================================================"
echo " DeepTutor is starting!"
echo ""
echo "   Open:  http://localhost:3782"
echo ""
echo "   Data lives at:  obsidian/deeptutor/"
echo ""
if $IS_FRESH; then
  echo "   Sync your wiki:  ./deeptutor/sync-wiki-to-deeptutor.sh"
fi
echo "============================================================"
